### PR TITLE
Do not replace event scripter

### PR DESCRIPTION
**Pull request by antlafarge**

### CODE REVIEW

**Comment by loeffelpan** [comment]
Sorry for late reply. Just tested your latest release not replacing eventscripter files.
I got some error in `docker-entrypoint.sh`. It refering to line 37 your changes here:
https://github.com/antlafarge/jdownloader/pull/35/commits/732774c76130ea1d42748dd81cb67b6114d61bd6#

```
2023-09-24T11:28:25+00:00| ________________________________________ CONTAINER STARTED _________________________________________
2023-09-24T11:28:25+00:00| OS = "Ubuntu 22.04.3 LTS"
./docker-entrypoint.sh: line 37: ii: command not found
./docker-entrypoint.sh: line 37: ii: command not found
2023-09-24T11:28:25+00:00| JAVA version = " "
2023-09-24T11:28:25+00:00| JAVA options = ""
2023-09-24T11:28:25+00:00| WARNING Environment variable 'JD_PASSWORD' is not set
2023-09-24T11:28:25+00:00| Delete any existing JDownloader installation files
2023-09-24T11:28:25+00:00| Download https://installer.jdownloader.org/JDownloader.jar
2023-09-24T11:28:26+00:00| Create cfg directory
2023-09-24T11:28:26+00:00| Write JDownloader download path in settings file
2023-09-24T11:28:26+00:00| Write myJDownloader settings file
2023-09-24T11:28:26+00:00| Replace JDownloader email in myJDownloader settings file
2023-09-24T11:28:26+00:00| Replace JDownloader devicename in myJDownloader settings file
2023-09-24T11:28:26+00:00| Start JDownloader
```

**Comment by antlafarge** [comment]
Hello I changed the code which extracts the java version, there is maybe a bug here.
But that's strange i used this last release without any problem but I will verify this.
This code is different under alpine, you Can use the alpine version by waiting for my tests and a fix.

**Comment by loeffelpan** [comment]
No fix needed. Image is working fine. Seems to be an cosmetic issue. But you have to verify as well. No hurry.

**Comment by antlafarge** [comment]
It should be fixed.

**Pull request closed without merging**
