### PR TITLE
Add support for rootless container

### PR DESCRIPTION
**Pull request by steled**
#### Reference Issue
#12

#### What does this implement/fix?
I added support for rootless alpine Docker container.

#### Any other comments?
No

### CODE REVIEW

**Comment by antlafarge** [comment]
There is a problem with your method. You set the UID and GID on the image build. When I publish an image to docker hub, the UID and GID the user wants to use is unknown. So your solution does work only if each user builds his own image from the source.

**Comment by steled** [comment]
Yes that's true but normally I would say the used UID and GID inside the container isn't that important.
I also checked how Docker creates their rootless images and they are also just using GID 1000 and UID 1000, see: https://github.com/docker-library/docker/blob/master/20.10/dind-rootless/Dockerfile#L18

So for me that qould be ok but depends on you.

**Comment by antlafarge** [comment]
Yes, anyway thank you for your help.

I thought about our problem.
The difference here is that we don't control the directories. The user who creates the container provides some directories where we need to be able to read/write, and we want this user to be able to read/write the files the container creates. So the container have to match the user informations of his creator.
I am doing some modifications to your pull request to allow this.

**Comment by antlafarge** [comment]
I test many modifications, you can look at this branch : 
https://github.com/antlafarge/jdownloader/tree/rootless

And you can try these tags : `dev-ubuntu` and `dev-alpine` in docker hub : 
https://hub.docker.com/repository/docker/antlafarge/jdownloader/tags?page=1&ordering=last_updated

The key of these modifications is the `user` parameter : 
https://github.com/antlafarge/jdownloader/blob/rootless/README.md#docker-run

**Comment by antlafarge** [comment]
If you can try this docker hub image and let me know if it works for you or if something (in the code or in the doc) could be improved.
I didn't tested `dev-alpine`, but I tested the `dev-ubuntu` image and it looks ok by my side.

**Comment by steled** [comment]
`dev-alpine` works for me... in k8s I just need to add:

````
...
spec:
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001
...
````

and it looks like:

````
$ ls -la
total 12356
drwxrwxrwx    1 root     root          4096 Jul  6 19:28 .
dr-xr-xr-x    1 root     root          4096 Jul  6 19:25 ..
-rw-r--r--    1 1001     1001       8367508 Jul  6 19:25 Core.jar
-rw-r--r--    1 1001     1001             0 Jul  6 19:25 JD2.lock
-rw-r--r--    1 1001     1001             4 Jul  6 19:25 JD2.port
-rwxr--r--    1 1001     1001       4125460 Jul  6 19:25 JDownloader.jar
-rw-r--r--    1 1001     1001             4 Jul  6 19:26 JDownloader.pid
-rw-r--r--    1 1001     1001           320 Jul  6 19:25 build.json
drwxr-xr-x    4 1001     1001          4096 Jul  6 19:28 cfg
-rwxrwxrwx    1 root     root          2698 Jul  2 11:44 docker-entrypoint.sh
drwxr-xr-x    2 1001     1001          4096 Jul  6 19:28 downloads
drwxr-xr-x    2 1001     1001          4096 Jul  6 19:25 extensions
-rwxrwxrwx    1 root     root          1129 Jul  2 11:41 functions.sh
drwxr-xr-x    2 1001     1001          4096 Jul  6 19:26 java
drwxr-xr-x    4 1001     1001          4096 Jul  6 19:26 jd
drwxr-xr-x    5 1001     1001          4096 Jul  6 19:25 libs
-rw-r--r--    1 1001     1001         32034 Jul  6 19:25 license.txt
-rw-r--r--    1 1001     1001         39624 Jul  6 19:25 license_german.txt
drwxr-xr-x    5 1001     1001          4096 Jul  6 19:25 licenses
drwxr-xr-x    6 1001     1001          4096 Jul  6 19:25 logs
-rwxrwxrwx    1 root     root          2650 May 31 23:42 setup.sh
drwxr-xr-x    3 1001     1001          4096 Jul  6 19:26 themes
drwxr-xr-x    6 1001     1001          4096 Jul  6 19:28 tmp
drwxr-xr-x    5 1001     1001          4096 Jul  6 19:26 translations
drwxr-xr-x    3 1001     1001          4096 Jul  6 19:25 update
````

**Comment by antlafarge** [comment]
It looks okay to add this parameters, isn't it?

**Pull request merged**
